refactor: make parent element computed
codelab-app/builder pull request #1819
Opened 2022-09-13 11:38 UTC by phmngocnghia

## Description (Optional)

## Related Issue(s)

Fixes #

2022-09-18 15:57 UTC, phmngocnghia commented
![image](https://user-images.githubusercontent.com/36730355/190916317-bb020d85-6b48-4e95-b968-5fe04162f1ba.png)

2022-09-19 12:19 UTC, webberwang requested changes

2022-09-19 12:19 UTC, webberwang commented on apps/builder-e2e/project.json
> -      // Need this empty block to forward the configurations
This comment should be left here

2022-09-19 12:19 UTC, webberwang commented on libs/frontend/modules/element/src/store/element-tree.model.ts
> +    const isElementNotInTree = (element: IElement) =>
instead of filtering out existing elements, we can call `updateCache` on existing elements

2022-09-19 12:19 UTC, webberwang commented on libs/frontend/modules/element/src/store/element-tree.model.ts
> +    newElements.forEach((element) => {
couldn't we share the same forEach loop?

2022-09-20 07:22 UTC, webberwang requested changes

2022-09-20 07:22 UTC, webberwang commented on libs/shared/abstract/core/src/domain/element/element.model.interface.ts
> +  parentElementFromId: Maybe<IElement>
`parentElementId` is good

2022-09-20 09:16 UTC, merged