Supports union type and enum type
codelab-app/builder pull request #1861
Opened 2022-09-22 10:24 UTC by hauleIT

## Description (Optional)

## Related Issue(s)

Fixes #1814

2022-09-22 17:46 UTC, webberwang requested changes

2022-09-22 17:46 UTC, webberwang commented on apps/cli/src/use-cases/parser/type-map.ts
> +  const isBaseCondition = apiField.type.indexOf('|') > -1
`includes` works too?

2022-09-22 17:46 UTC, webberwang commented on apps/cli/src/use-cases/parser/type-map.ts
> +    values.includes('small') ||
I thought we used the CODE logic for enum, this hard coding words isn't good

2022-09-26 10:27 UTC, webberwang requested changes

2022-09-26 10:27 UTC, webberwang commented on apps/cli/src/use-cases/parser/type-map.ts
> +    case 'number | string': {
for all these strings, we should split as array, then use a single function to check instead of having separate cases

2022-09-26 10:27 UTC, webberwang commented on apps/cli/src/use-cases/parser/type-map.ts
> +  if (apiField.isEnum) {
we should have a file for each type, then import related functions here

2022-09-26 10:28 UTC, webberwang requested changes

2022-09-26 10:28 UTC, webberwang commented on apps/cli/src/use-cases/parser/type-map.ts
> +  const a = values
use a more description variable

2022-09-27 15:52 UTC, webberwang requested changes

2022-09-27 15:52 UTC, webberwang commented on apps/cli/src/use-cases/parser/type-map.ts
> +  const isBaseCondition = apiField.type.indexOf('|') > -1
why not use includes instead?

2022-09-27 15:53 UTC, webberwang commented on apps/cli/src/use-cases/parser/type-map.ts
> +    case 'number | string': {
@hauleIT any thoughts on this?

2022-09-27 15:56 UTC, webberwang commented on apps/cli/src/use-cases/parser/type-map.ts
> +  const isBaseCondition = apiField.type.indexOf('|') > -1
@hauleIT thoughts?

2022-09-27 15:58 UTC, webberwang requested changes

2022-09-27 15:58 UTC, webberwang commented on apps/cli/src/use-cases/parser/types/union-type-map.ts
> +  const getKeyObjInUnion = (data: string, choose: string) => {
this can be replaced by learning regex, it's a bit hard but much more concise

2022-09-28 08:04 UTC, hauleIT commented on apps/cli/src/use-cases/parser/type-map.ts
> +    case 'number | string': {
Yes, I will try

2022-09-28 08:06 UTC, hauleIT commented on apps/cli/src/use-cases/parser/types/union-type-map.ts
> +  const getKeyObjInUnion = (data: string, choose: string) => {
I got it, I will research regex

2022-09-29 12:52 UTC, webberwang requested changes
- [ ] any instances of primitive string types should use an enum we create specifically for the ant design docs string format

2022-09-29 12:52 UTC, webberwang commented on apps/cli/src/use-cases/parser/type-map.ts
> +  if (isBaseCondition) {
why not name it to `isUnionType`? Also we should have `!isEnum` requirement as well. We are relying on `isEnum` check being first (which isn't ideal).

2022-10-04 02:58 UTC, webberwang requested changes

2022-10-04 02:58 UTC, webberwang commented on apps/cli/src/use-cases/seed/types/union-type-map.ts
> +  const getKeyObjInUnion = (data: string, choose: string) => {
Could you comment what this function does? Can be replaced with a regex

2022-10-11 10:17 UTC, closed without merging