feat: resolver get base types
codelab-app/builder pull request #1881
Opened 2022-09-30 07:16 UTC by phmngocnghia

## Description 
-TypeBase should be a type, implement ITypeBase (should be created) because we can't return interface structure
- Other types implement ITypebase too

```graphql
  input GetBaseTypesOptions {
    limit: Int
    offset: Int
  }

  type GetBaseTypesReturn {
    items: [BaseType!]!
    totalCount: Int!
  }

query {
   baseTypes(
    options: GetBaseTypesOptions
   ):GetBaseTypesReturn!
}
```

```graphql
query ($options: GetBaseTypesOptions) {
	baseTypes(options: $options) {
		totalCount
		items {
	    id
			name
			kind
			owner {
				id
			}
		}
	}
}
```

## Related Issue(s)

Fixes #1820

2022-09-30 13:00 UTC, webberwang requested changes

2022-09-30 13:00 UTC, webberwang commented on libs/shared/abstract/core/src/domain/type/fragments/array-type.fragment.graphql
>    ...TypeBase
`BaseType`?

2022-10-01 03:45 UTC, phmngocnghia commented on libs/backend/application/src/repositories/type/type.repo.ts
> +  baseTypes: async (
![image](https://user-images.githubusercontent.com/36730355/193386111-6e21123e-a731-43ea-8825-461958237af3.png)

OGM doesn't work with the interface. ^ won't work

I query using custom `Type` label

2022-10-01 03:45 UTC, phmngocnghia commented on libs/backend/application/src/repositories/type/type.repo.ts
> +  countBaseTypes: async (txn: Transaction, offset = 0): Promise<number> => {
https://github.com/codelab-app/builder/pull/1881#discussion_r985037505

2022-10-03 07:19 UTC, webberwang requested changes

2022-10-03 07:19 UTC, webberwang commented on libs/backend/application/src/repositories/type/type.repo.ts
> +    params: any,
type it with generated code

2022-10-03 07:19 UTC, webberwang commented on libs/backend/application/src/repositories/type/type.repo.ts
> +type BaseType = any
shouldn't use any type

2022-10-03 07:19 UTC, webberwang commented on libs/backend/application/src/repositories/type/type.repo.ts
> +        dataMapper(record as Record<GetBaseTypesRecord>),
avoid casting if possible

2022-10-03 07:19 UTC, webberwang commented on libs/backend/graphql/src/resolvers/type/query/baseTypes.resolver.ts
> +export const baseTypes: IFieldResolver<any, any, QueryBaseTypesArgs> =
don't use any, we have generated types

2022-10-03 07:35 UTC, phmngocnghia commented on libs/backend/application/src/repositories/type/type.repo.ts
> +        dataMapper(record as Record<GetBaseTypesRecord>),
cast is needed because the type definition of the library doesn't have a way to define the generic type of running transaction

2022-10-04 02:54 UTC, webberwang requested changes

2022-10-04 02:54 UTC, webberwang commented on libs/backend/application/src/repositories/type/type.repo.ts
> +        dataMapper(record as Record<GetBaseTypesRecord>),
check out our other resolvers, we don't use any casting there

2022-10-04 02:54 UTC, webberwang commented on libs/backend/application/src/repositories/type/type.repo.ts
> +    params: any,
don't use any here

2022-10-04 02:54 UTC, webberwang commented on libs/backend/application/src/repositories/type/type.repo.ts
> +type BaseType = any
don't use any here

2022-10-04 02:54 UTC, webberwang commented on libs/backend/graphql/src/resolvers/type/query/baseTypes.resolver.ts
> +export const baseTypes: IFieldResolver<any, any, QueryBaseTypesArgs> =
don't use any here

2022-10-05 02:20 UTC, merged