fix: filter out props keys that are not defined in atom api
codelab-app/builder pull request #1928
Opened 2022-10-12 20:50 UTC by melhamin

## Description (Optional)

This PR includes a frontend solution for removing props that are left over in elements props after deleting it from atom's api. Replaces existing solution that updates element element props after the prop is deleted from atom's api.

## Related Issue(s)

Fixes #1758

2022-10-12 22:07 UTC, webberwang requested changes

2022-10-12 22:07 UTC, webberwang commented on libs/frontend/domain/renderer/src/element/ElementWrapper.ts
> +  if (element.atom?.current.api.current) {
unit specs failing, try `maybeCurrent`

2022-10-12 22:07 UTC, webberwang commented on libs/frontend/domain/renderer/src/element/ElementWrapper.ts
> +    keysToOmit.forEach((key) => element.props?.delete(key))
I'm thinking the prop model should have a reference to an interface type? This way we can move all the logic there

That would make sense domain wise, since dats shape is dependent on the interface

2022-10-13 18:05 UTC, melhamin commented on libs/frontend/domain/renderer/src/element/ElementWrapper.ts
> +    keysToOmit.forEach((key) => element.props?.delete(key))
Yeah it makes sense, if we have the interface type in prop model. Will try that

2022-10-15 00:31 UTC, webberwang requested changes

2022-10-15 00:31 UTC, webberwang commented on libs/frontend/domain/prop/src/store/prop.model.ts
> +import { difference, keys, values } from 'lodash'
here we do want to import using `lodash/*` etc

2022-10-15 00:31 UTC, webberwang commented on libs/frontend/domain/renderer/src/element/ElementWrapper.ts
> +// eslint-disable-next-line lodash/import-scope
remove this

2022-10-15 00:31 UTC, webberwang commented on libs/frontend/domain/prop/src/store/prop.model.ts
> +      keysToOmit.forEach((key) => this.delete(key))
add https://typescript-eslint.io/rules/no-dynamic-delete/ to root eslint, let's use a map reduce strategy

https://www.npmjs.com/package/omit-deep-lodash

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/26264925/195960759-2330e1a8-9379-4ca7-a5ef-da9f6378398b.jpg)

2022-10-15 20:00 UTC, melhamin commented on libs/frontend/domain/prop/src/store/prop.model.ts
> +      keysToOmit.forEach((key) => this.delete(key))
Why do we need to add no-dynamic-delete rule?

2022-10-15 20:02 UTC, webberwang commented on libs/frontend/domain/prop/src/store/prop.model.ts
> +      keysToOmit.forEach((key) => this.delete(key))
don't think it's good practice as it's mutable
![no-dynamic-delete___TypeScript_ESLint](https://user-images.githubusercontent.com/26264925/196005584-fa6bf060-8f37-43ca-a28c-83961ddb7232.jpg)

2022-10-15 20:05 UTC, melhamin commented on libs/frontend/domain/prop/src/store/prop.model.ts
> +      keysToOmit.forEach((key) => this.delete(key))
We are not using dynamic delete here

2022-10-15 21:14 UTC, webberwang commented on libs/frontend/domain/prop/src/store/prop.model.ts
> +      keysToOmit.forEach((key) => this.delete(key))
oh nevermind, also it's already added

2022-10-15 21:16 UTC, melhamin commented on libs/frontend/domain/prop/src/store/prop.model.ts
> +      keysToOmit.forEach((key) => this.delete(key))
Should still use https://www.npmjs.com/package/omit-deep-lodash? both would be the same, just one extra package dependency.

2022-10-15 21:19 UTC, webberwang commented on libs/frontend/domain/prop/src/store/prop.model.ts
> +      keysToOmit.forEach((key) => this.delete(key))
Could try this https://stackoverflow.com/a/53398058/2159920

2022-10-16 07:01 UTC, melhamin commented on libs/frontend/domain/prop/src/store/prop.model.ts
> +      keysToOmit.forEach((key) => this.delete(key))
I want to use [omitBy](https://lodash.com/docs/4.17.15#omitBy) instead. Seem better and cleaner solution than omit.

2022-11-05 14:13 UTC, merged