feat(apps-landing): add community email modal
codelab-app/builder pull request #2035
Opened 2022-11-18 23:58 UTC by JLL32

## Description (Optional)

Add a modal for the community feature to collect audience emails
### States
modal
<img width="683" alt="Screenshot 2022-11-19 at 00 51 51" src="https://user-images.githubusercontent.com/26872714/202822030-d99feb6f-675b-4b80-ad0f-8c7e84db06a4.png">

modal, valid email
<img width="665" alt="Screenshot 2022-11-19 at 00 52 14" src="https://user-images.githubusercontent.com/26872714/202822093-75c5659e-23d8-4b34-82c2-58a241f3e56e.png">

modal, invalid email
<img width="725" alt="Screenshot 2022-11-19 at 00 52 24" src="https://user-images.githubusercontent.com/26872714/202822176-069ae7bd-0342-4e28-9f61-8b8424435964.png">

notification, success
<img width="412" alt="Screenshot 2022-11-19 at 00 53 42" src="https://user-images.githubusercontent.com/26872714/202822215-4d0717f3-5777-4c00-b2c3-3d631b13ecec.png">

notification, failure
<img width="1272" alt="Screenshot 2022-11-19 at 00 53 22" src="https://user-images.githubusercontent.com/26872714/202822239-3cffe74f-f701-4441-b495-c69172bfb53b.png">

## Related Issue(s)

Makes progress #1994

2022-11-21 01:21 UTC, webberwang requested changes

2022-11-21 01:21 UTC, webberwang commented on apps/landing/home/community/EmailModal.tsx
> +interface EmailModalProps {
why recreate interface when we can re-use existing?

2022-11-21 01:21 UTC, webberwang commented on apps/landing/pages/api/community/email.ts
> +const LIST_ID = process.env.MAILCHIMP_LIST_ID || ''
possible to move to `shared-env`?

let's have `landing-env.ts` and `builder-env.ts`

2022-11-23 10:45 UTC, JLL32 commented on apps/landing/home/community/EmailModal.tsx
> +interface EmailModalProps {
The defined type is a bit different, I have expressed that difference in the new declaration

2022-11-24 16:00 UTC, JLL32 commented on apps/landing/pages/api/community/email.ts
> +const LIST_ID = process.env.MAILCHIMP_LIST_ID || ''
addressed

2022-11-25 18:15 UTC, merged