fix: highlighted type based on query param (#2053)
codelab-app/builder pull request #2076
Opened 2022-12-05 22:07 UTC by M-Abozaid

* feat: get typeBase query page based on type id option
* fix: fetch types page base on typeId from query param

## Description (Optional)

## Related Issue(s)

Fixes #2053

2022-12-05 22:08 UTC, M-Abozaid commented
https://user-images.githubusercontent.com/23200283/205752756-68b62fbc-874e-4b55-98af-e6a3da91607c.mp4

2022-12-06 07:51 UTC, webberwang requested changes

2022-12-06 07:51 UTC, webberwang commented on libs/backend/application/src/repositories/type/type.repo.ts
> +      offset = Math.floor(index / limit) * limit
what's the need for this `offset` calculation?

2022-12-06 07:51 UTC, webberwang commented on libs/frontend/abstract/core/src/domain/type/type.service.interface.ts
> +  highlightedTypeId: Nullable<string>
we could pass those in as query params instead

2022-12-06 09:53 UTC, webberwang requested changes

2022-12-06 09:53 UTC, webberwang commented on libs/backend/infra/adapter/neo4j/src/cypher/type/getTypeIndex.cypher
> +MATCH (type:Type)
why is this needed?

2022-12-06 13:29 UTC, M-Abozaid commented on libs/backend/application/src/repositories/type/type.repo.ts
> +      offset = Math.floor(index / limit) * limit
The `offset` is needed to tell the frontend which page is selected

2022-12-06 13:34 UTC, M-Abozaid commented on libs/frontend/abstract/core/src/domain/type/type.service.interface.ts
> +  highlightedTypeId: Nullable<string>
the value of the `typeId` is deleted from the url query after first render and before the table data is fetched, the `highlightedTypeId` is needed to persist the value until the table is rendered and the type is expanded

2022-12-06 13:34 UTC, M-Abozaid commented on libs/backend/infra/adapter/neo4j/src/cypher/type/getTypeIndex.cypher
> +MATCH (type:Type)
this is needed to figure out which page the selected type is in.

2022-12-08 00:04 UTC, webberwang commented on libs/backend/infra/adapter/neo4j/src/cypher/type/getTypeIndex.cypher
> +MATCH (type:Type)
this could all be done in the frontend

2022-12-08 00:05 UTC, webberwang commented on libs/frontend/domain/type/src/store/type.service.ts
> +          id: this.highlightedTypeId,
the information should already be in mobx

2022-12-27 07:29 UTC, closed without merging