refactor(apps-builder): move store to the left pane
codelab-app/builder pull request #2162
Opened 2023-01-12 07:59 UTC by JLL32

## Description

Moves both state and actions to the left pane

## Video or Image

<-- Add video or image showing how the new feature works -->

## Related Issue(s)

Fixes #2041

2023-01-15 06:55 UTC, webberwang requested changes

2023-01-15 06:55 UTC, webberwang commented on libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx
> +const Container = styled.div`
Use tw/css on `Tabs` component instead

2023-01-16 11:24 UTC, JLL32 commented on libs/frontend/domain/builder/src/sections/explorer-pane/BuilderExplorerPane.tsx
> +const Container = styled.div`
addressed

2023-01-16 16:49 UTC, webberwang commented on apps/builder-e2e/src/e2e/css.cy.ts
> +        .type(createBackgroundColorStyle(backgroundColor1), { delay: 100 })
instead delay we can assert label exists?

2023-01-16 16:50 UTC, webberwang commented on libs/frontend/domain/builder/src/sections/editor-pane/EditorPane-Builder.tsx
> +    return <Container></Container>
What happened here?

2023-01-18 09:37 UTC, JLL32 commented on apps/builder-e2e/src/e2e/css.cy.ts
> +        .type(createBackgroundColorStyle(backgroundColor1), { delay: 100 })
tried multiple solutions and the delay was the only solution that made the tests stable so far. should I decrease the amount?

2023-01-18 09:37 UTC, JLL32 commented on libs/frontend/domain/builder/src/sections/editor-pane/EditorPane-Builder.tsx
> +    return <Container></Container>
After moving its elements to the left pane I left it as a placeholder so that I can reuse it later for input modals

2023-01-22 19:19 UTC, JLL32 commented on apps/builder-e2e/src/e2e/css.cy.ts
> +        .type(createBackgroundColorStyle(backgroundColor1), { delay: 100 })
the delay has been removed for now until we find a better solution

2023-01-23 11:28 UTC, merged