feat: integrate react-grid-layout as atom
codelab-app/builder pull request #2185
Opened 2023-01-18 09:07 UTC by tinhw3

## Description

## Video or Image

https://user-images.githubusercontent.com/117329462/213129391-dffcd512-aa1a-45e6-839c-4357014ddefd.mov

## Related Issue(s)

Fixes #2047

2023-01-19 02:51 UTC, webberwang requested changes

2023-01-19 02:51 UTC, webberwang commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +        {...restProps}
We should de-structure props and explicitly override the props with default values like `breakpoints` etc

2023-01-19 02:51 UTC, webberwang commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +    const layouts = restProps.layouts || {}
create `makeLayout` function

2023-01-19 03:00 UTC, webberwang requested changes

2023-01-19 03:00 UTC, webberwang commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +        })) as Array<Layout>
could try https://www.npmjs.com/package/object-typed to preserve types so we may not have to cast

2023-01-30 08:22 UTC, webberwang requested changes

2023-01-30 08:22 UTC, webberwang commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +            static: restProps.static,
cast earlier at the `Layout` level

2023-01-30 08:22 UTC, webberwang commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +            cols[key] = restProps.cols[key]!
is `!` needed?

2023-01-30 08:24 UTC, webberwang requested changes

2023-01-30 08:24 UTC, webberwang commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +    const isComponentMountedFirstTime = useRef(false)
is there a better way for this?

2023-01-30 08:25 UTC, tinhw3 commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +            cols[key] = restProps.cols[key]!
so weird that vscode warning `restProps.cols[key]` is `number | undefined`

2023-01-30 09:18 UTC, tinhw3 commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +    const isComponentMountedFirstTime = useRef(false)
you mean for this `isComponentMountedFirstTime`?

2023-01-30 09:42 UTC, tinhw3 commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +            static: restProps.static,
Sorry @webberwang , I dont understand this one. Do you mean using `ele. static = restProps.static`?

2023-01-30 17:58 UTC, webberwang commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +    const isComponentMountedFirstTime = useRef(false)
right

2023-01-30 17:59 UTC, webberwang commented on libs/frontend/platform/atoms/src/custom/grid-layout/GridLayout.tsx
> +            static: restProps.static,
I mean cast `as Layout` instead somewhere

2023-01-31 07:00 UTC, merged